// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: event_payloads_v1.proto

package eventsv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Allowed message types. Extendable via new enum values.
type ChatEvent_EventType int32

const (
	ChatEvent_UNSPECIFIED ChatEvent_EventType = 0
	ChatEvent_EVENT       ChatEvent_EventType = 1
	ChatEvent_TEXT        ChatEvent_EventType = 2
	ChatEvent_ATTACHMENT  ChatEvent_EventType = 3
	ChatEvent_REACTION    ChatEvent_EventType = 7
	ChatEvent_ENCRYPTED   ChatEvent_EventType = 6 // opaque ciphertext
	ChatEvent_SYSTEM      ChatEvent_EventType = 10
	ChatEvent_CALL_OFFER  ChatEvent_EventType = 21
	ChatEvent_CALL_ANSWER ChatEvent_EventType = 22
	ChatEvent_CALL_ICE    ChatEvent_EventType = 23
	ChatEvent_CALL_END    ChatEvent_EventType = 24
)

// Enum value maps for ChatEvent_EventType.
var (
	ChatEvent_EventType_name = map[int32]string{
		0:  "UNSPECIFIED",
		1:  "EVENT",
		2:  "TEXT",
		3:  "ATTACHMENT",
		7:  "REACTION",
		6:  "ENCRYPTED",
		10: "SYSTEM",
		21: "CALL_OFFER",
		22: "CALL_ANSWER",
		23: "CALL_ICE",
		24: "CALL_END",
	}
	ChatEvent_EventType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"EVENT":       1,
		"TEXT":        2,
		"ATTACHMENT":  3,
		"REACTION":    7,
		"ENCRYPTED":   6,
		"SYSTEM":      10,
		"CALL_OFFER":  21,
		"CALL_ANSWER": 22,
		"CALL_ICE":    23,
		"CALL_END":    24,
	}
)

func (x ChatEvent_EventType) Enum() *ChatEvent_EventType {
	p := new(ChatEvent_EventType)
	*p = x
	return p
}

func (x ChatEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChatEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_event_payloads_v1_proto_enumTypes[0].Descriptor()
}

func (ChatEvent_EventType) Type() protoreflect.EnumType {
	return &file_event_payloads_v1_proto_enumTypes[0]
}

func (x ChatEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChatEvent_EventType.Descriptor instead.
func (ChatEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_event_payloads_v1_proto_rawDescGZIP(), []int{0, 0}
}

// Indicates priority of delivery to prioritize critical events (e.g., CALL_OFFER).
type EventBroadcast_Priority int32

const (
	EventBroadcast_NORMAL EventBroadcast_Priority = 0
	EventBroadcast_HIGH   EventBroadcast_Priority = 1
)

// Enum value maps for EventBroadcast_Priority.
var (
	EventBroadcast_Priority_name = map[int32]string{
		0: "NORMAL",
		1: "HIGH",
	}
	EventBroadcast_Priority_value = map[string]int32{
		"NORMAL": 0,
		"HIGH":   1,
	}
)

func (x EventBroadcast_Priority) Enum() *EventBroadcast_Priority {
	p := new(EventBroadcast_Priority)
	*p = x
	return p
}

func (x EventBroadcast_Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventBroadcast_Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_event_payloads_v1_proto_enumTypes[1].Descriptor()
}

func (EventBroadcast_Priority) Type() protoreflect.EnumType {
	return &file_event_payloads_v1_proto_enumTypes[1]
}

func (x EventBroadcast_Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventBroadcast_Priority.Descriptor instead.
func (EventBroadcast_Priority) EnumDescriptor() ([]byte, []int) {
	return file_event_payloads_v1_proto_rawDescGZIP(), []int{2, 0}
}

// ChatEvent represents an event in the chat system, the core unit of data flowing
// through the system in real-time to end-user devices.
type ChatEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the event, constrained for quick parsing and validation.
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Identifies the chat room or context, ensuring data is routed to the correct group.
	RoomId string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Identifies the originator of the event, crucial for attribution and security.
	// Marked optional as it may not be required for system messages.
	SenderId *string `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3,oneof" json:"sender_id,omitempty"`
	// Categorizes the event (e.g., TEXT, ATTACHMENT) for efficient handling.
	EventType ChatEvent_EventType `protobuf:"varint,4,opt,name=event_type,json=eventType,proto3,enum=events.v1.ChatEvent_EventType" json:"event_type,omitempty"`
	// Timestamp for event creation, aiding in ordering and latency debugging.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Version field to handle future changes without breaking existing clients.
	Version       int32 `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatEvent) Reset() {
	*x = ChatEvent{}
	mi := &file_event_payloads_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatEvent) ProtoMessage() {}

func (x *ChatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_payloads_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatEvent.ProtoReflect.Descriptor instead.
func (*ChatEvent) Descriptor() ([]byte, []int) {
	return file_event_payloads_v1_proto_rawDescGZIP(), []int{0}
}

func (x *ChatEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ChatEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ChatEvent) GetSenderId() string {
	if x != nil && x.SenderId != nil {
		return *x.SenderId
	}
	return ""
}

func (x *ChatEvent) GetEventType() ChatEvent_EventType {
	if x != nil {
		return x.EventType
	}
	return ChatEvent_UNSPECIFIED
}

func (x *ChatEvent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ChatEvent) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// DeliveryTarget represents an entry for delivery to a specific recipient,
// facilitating the distribution phase of data flow.
type DeliveryTarget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifies the target user or device for precise routing.
	RecepientId string `protobuf:"bytes,1,opt,name=recepient_id,json=recepientId,proto3" json:"recepient_id,omitempty"`
	// Unique identifier for tracking delivery status and retries in real-time.
	OutboxId      string `protobuf:"bytes,2,opt,name=outbox_id,json=outboxId,proto3" json:"outbox_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryTarget) Reset() {
	*x = DeliveryTarget{}
	mi := &file_event_payloads_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryTarget) ProtoMessage() {}

func (x *DeliveryTarget) ProtoReflect() protoreflect.Message {
	mi := &file_event_payloads_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryTarget.ProtoReflect.Descriptor instead.
func (*DeliveryTarget) Descriptor() ([]byte, []int) {
	return file_event_payloads_v1_proto_rawDescGZIP(), []int{1}
}

func (x *DeliveryTarget) GetRecepientId() string {
	if x != nil {
		return x.RecepientId
	}
	return ""
}

func (x *DeliveryTarget) GetOutboxId() string {
	if x != nil {
		return x.OutboxId
	}
	return ""
}

// EventBroadcast encapsulates an event and its delivery targets for bulk distribution
// to multiple recipients, optimizing the initial broadcast phase.
type EventBroadcast struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The event to be distributed.
	Event *ChatEvent `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	// List of delivery targets specifying recipients for batch processing efficiency.
	Targets       []*DeliveryTarget       `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
	Priority      EventBroadcast_Priority `protobuf:"varint,3,opt,name=priority,proto3,enum=events.v1.EventBroadcast_Priority" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventBroadcast) Reset() {
	*x = EventBroadcast{}
	mi := &file_event_payloads_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBroadcast) ProtoMessage() {}

func (x *EventBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_event_payloads_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBroadcast.ProtoReflect.Descriptor instead.
func (*EventBroadcast) Descriptor() ([]byte, []int) {
	return file_event_payloads_v1_proto_rawDescGZIP(), []int{2}
}

func (x *EventBroadcast) GetEvent() *ChatEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *EventBroadcast) GetTargets() []*DeliveryTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *EventBroadcast) GetPriority() EventBroadcast_Priority {
	if x != nil {
		return x.Priority
	}
	return EventBroadcast_NORMAL
}

// UserDelivery represents the final payload delivered to an end-user device,
// containing the event, specific delivery target, and detailed data.
type UserDelivery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The event data being delivered.
	Event *ChatEvent `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	// Specific delivery target for this delivery, aiding in tracking.
	Target *DeliveryTarget `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// Flexible struct for detailed event data (e.g., message text, media metadata).
	Payload *structpb.Struct `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Indicates if payload data is compressed to save bandwidth for large messages.
	IsCompressed bool `protobuf:"varint,4,opt,name=is_compressed,json=isCompressed,proto3" json:"is_compressed,omitempty"`
	// Metadata for retry logic to ensure robust delivery to end-user devices.
	RetryCount    int32 `protobuf:"varint,5,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDelivery) Reset() {
	*x = UserDelivery{}
	mi := &file_event_payloads_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDelivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDelivery) ProtoMessage() {}

func (x *UserDelivery) ProtoReflect() protoreflect.Message {
	mi := &file_event_payloads_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDelivery.ProtoReflect.Descriptor instead.
func (*UserDelivery) Descriptor() ([]byte, []int) {
	return file_event_payloads_v1_proto_rawDescGZIP(), []int{3}
}

func (x *UserDelivery) GetEvent() *ChatEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *UserDelivery) GetTarget() *DeliveryTarget {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *UserDelivery) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UserDelivery) GetIsCompressed() bool {
	if x != nil {
		return x.IsCompressed
	}
	return false
}

func (x *UserDelivery) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

var File_event_payloads_v1_proto protoreflect.FileDescriptor

const file_event_payloads_v1_proto_rawDesc = "" +
	"\n" +
	"\x17event_payloads_v1.proto\x12\tevents.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x84\x04\n" +
	"\tChatEvent\x126\n" +
	"\bevent_id\x18\x01 \x01(\tB\x1b\xbaH\x18r\x16\x10\x03\x18(2\x10[0-9a-z_-]{3,20}R\aeventId\x124\n" +
	"\aroom_id\x18\x02 \x01(\tB\x1b\xbaH\x18r\x16\x10\x03\x18(2\x10[0-9a-z_-]{3,20}R\x06roomId\x12=\n" +
	"\tsender_id\x18\x03 \x01(\tB\x1b\xbaH\x18r\x16\x10\x03\x18(2\x10[0-9a-z_-]{3,20}H\x00R\bsenderId\x88\x01\x01\x12=\n" +
	"\n" +
	"event_type\x18\x04 \x01(\x0e2\x1e.events.v1.ChatEvent.EventTypeR\teventType\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x05R\aversion\"\xa7\x01\n" +
	"\tEventType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\t\n" +
	"\x05EVENT\x10\x01\x12\b\n" +
	"\x04TEXT\x10\x02\x12\x0e\n" +
	"\n" +
	"ATTACHMENT\x10\x03\x12\f\n" +
	"\bREACTION\x10\a\x12\r\n" +
	"\tENCRYPTED\x10\x06\x12\n" +
	"\n" +
	"\x06SYSTEM\x10\n" +
	"\x12\x0e\n" +
	"\n" +
	"CALL_OFFER\x10\x15\x12\x0f\n" +
	"\vCALL_ANSWER\x10\x16\x12\f\n" +
	"\bCALL_ICE\x10\x17\x12\f\n" +
	"\bCALL_END\x10\x18B\f\n" +
	"\n" +
	"_sender_id\"\x8a\x01\n" +
	"\x0eDeliveryTarget\x12>\n" +
	"\frecepient_id\x18\x01 \x01(\tB\x1b\xbaH\x18r\x16\x10\x03\x18(2\x10[0-9a-z_-]{3,20}R\vrecepientId\x128\n" +
	"\toutbox_id\x18\x02 \x01(\tB\x1b\xbaH\x18r\x16\x10\x03\x18(2\x10[0-9a-z_-]{3,20}R\boutboxId\"\xd3\x01\n" +
	"\x0eEventBroadcast\x12*\n" +
	"\x05event\x18\x01 \x01(\v2\x14.events.v1.ChatEventR\x05event\x123\n" +
	"\atargets\x18\x02 \x03(\v2\x19.events.v1.DeliveryTargetR\atargets\x12>\n" +
	"\bpriority\x18\x03 \x01(\x0e2\".events.v1.EventBroadcast.PriorityR\bpriority\" \n" +
	"\bPriority\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x00\x12\b\n" +
	"\x04HIGH\x10\x01\"\xe6\x01\n" +
	"\fUserDelivery\x12*\n" +
	"\x05event\x18\x01 \x01(\v2\x14.events.v1.ChatEventR\x05event\x121\n" +
	"\x06target\x18\x02 \x01(\v2\x19.events.v1.DeliveryTargetR\x06target\x121\n" +
	"\apayload\x18\x03 \x01(\v2\x17.google.protobuf.StructR\apayload\x12#\n" +
	"\ris_compressed\x18\x04 \x01(\bR\fisCompressed\x12\x1f\n" +
	"\vretry_count\x18\x05 \x01(\x05R\n" +
	"retryCountB\x98\x01\n" +
	"\rcom.events.v1B\x14EventPayloadsV1ProtoP\x01Z,github.com/antinvestor/service-chat;eventsv1\xa2\x02\x03EXX\xaa\x02\tEvents.V1\xca\x02\tEvents\\V1\xe2\x02\x15Events\\V1\\GPBMetadata\xea\x02\n" +
	"Events::V1b\x06proto3"

var (
	file_event_payloads_v1_proto_rawDescOnce sync.Once
	file_event_payloads_v1_proto_rawDescData []byte
)

func file_event_payloads_v1_proto_rawDescGZIP() []byte {
	file_event_payloads_v1_proto_rawDescOnce.Do(func() {
		file_event_payloads_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_payloads_v1_proto_rawDesc), len(file_event_payloads_v1_proto_rawDesc)))
	})
	return file_event_payloads_v1_proto_rawDescData
}

var file_event_payloads_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_event_payloads_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_event_payloads_v1_proto_goTypes = []any{
	(ChatEvent_EventType)(0),      // 0: events.v1.ChatEvent.EventType
	(EventBroadcast_Priority)(0),  // 1: events.v1.EventBroadcast.Priority
	(*ChatEvent)(nil),             // 2: events.v1.ChatEvent
	(*DeliveryTarget)(nil),        // 3: events.v1.DeliveryTarget
	(*EventBroadcast)(nil),        // 4: events.v1.EventBroadcast
	(*UserDelivery)(nil),          // 5: events.v1.UserDelivery
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 7: google.protobuf.Struct
}
var file_event_payloads_v1_proto_depIdxs = []int32{
	0, // 0: events.v1.ChatEvent.event_type:type_name -> events.v1.ChatEvent.EventType
	6, // 1: events.v1.ChatEvent.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: events.v1.EventBroadcast.event:type_name -> events.v1.ChatEvent
	3, // 3: events.v1.EventBroadcast.targets:type_name -> events.v1.DeliveryTarget
	1, // 4: events.v1.EventBroadcast.priority:type_name -> events.v1.EventBroadcast.Priority
	2, // 5: events.v1.UserDelivery.event:type_name -> events.v1.ChatEvent
	3, // 6: events.v1.UserDelivery.target:type_name -> events.v1.DeliveryTarget
	7, // 7: events.v1.UserDelivery.payload:type_name -> google.protobuf.Struct
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_event_payloads_v1_proto_init() }
func file_event_payloads_v1_proto_init() {
	if File_event_payloads_v1_proto != nil {
		return
	}
	file_event_payloads_v1_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_payloads_v1_proto_rawDesc), len(file_event_payloads_v1_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_payloads_v1_proto_goTypes,
		DependencyIndexes: file_event_payloads_v1_proto_depIdxs,
		EnumInfos:         file_event_payloads_v1_proto_enumTypes,
		MessageInfos:      file_event_payloads_v1_proto_msgTypes,
	}.Build()
	File_event_payloads_v1_proto = out.File
	file_event_payloads_v1_proto_goTypes = nil
	file_event_payloads_v1_proto_depIdxs = nil
}
