// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: event_payloads_v1.proto

package eventsv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Allowed message types. Extendable via new enum values.
type EventLink_EventType int32

const (
	EventLink_SYSTEM          EventLink_EventType = 0
	EventLink_EVENT           EventLink_EventType = 1
	EventLink_TEXT            EventLink_EventType = 2
	EventLink_ATTACHMENT      EventLink_EventType = 3
	EventLink_REACTION        EventLink_EventType = 7
	EventLink_ENCRYPTED       EventLink_EventType = 6 // opaque ciphertext
	EventLink_EDIT            EventLink_EventType = 8 // represents event overriding another
	EventLink_REDACTION       EventLink_EventType = 9 // represents event deleting another
	EventLink_STATE_DELIVERED EventLink_EventType = 10
	EventLink_STATE_READ      EventLink_EventType = 11
	EventLink_STATE_TYPING    EventLink_EventType = 12
	EventLink_PRESENCE        EventLink_EventType = 17
	EventLink_CALL_OFFER      EventLink_EventType = 21
	EventLink_CALL_ANSWER     EventLink_EventType = 22
	EventLink_CALL_ICE        EventLink_EventType = 23
	EventLink_CALL_END        EventLink_EventType = 24
)

// Enum value maps for EventLink_EventType.
var (
	EventLink_EventType_name = map[int32]string{
		0:  "SYSTEM",
		1:  "EVENT",
		2:  "TEXT",
		3:  "ATTACHMENT",
		7:  "REACTION",
		6:  "ENCRYPTED",
		8:  "EDIT",
		9:  "REDACTION",
		10: "STATE_DELIVERED",
		11: "STATE_READ",
		12: "STATE_TYPING",
		17: "PRESENCE",
		21: "CALL_OFFER",
		22: "CALL_ANSWER",
		23: "CALL_ICE",
		24: "CALL_END",
	}
	EventLink_EventType_value = map[string]int32{
		"SYSTEM":          0,
		"EVENT":           1,
		"TEXT":            2,
		"ATTACHMENT":      3,
		"REACTION":        7,
		"ENCRYPTED":       6,
		"EDIT":            8,
		"REDACTION":       9,
		"STATE_DELIVERED": 10,
		"STATE_READ":      11,
		"STATE_TYPING":    12,
		"PRESENCE":        17,
		"CALL_OFFER":      21,
		"CALL_ANSWER":     22,
		"CALL_ICE":        23,
		"CALL_END":        24,
	}
)

func (x EventLink_EventType) Enum() *EventLink_EventType {
	p := new(EventLink_EventType)
	*p = x
	return p
}

func (x EventLink_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventLink_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_event_payloads_v1_proto_enumTypes[0].Descriptor()
}

func (EventLink_EventType) Type() protoreflect.EnumType {
	return &file_event_payloads_v1_proto_enumTypes[0]
}

func (x EventLink_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventLink_EventType.Descriptor instead.
func (EventLink_EventType) EnumDescriptor() ([]byte, []int) {
	return file_event_payloads_v1_proto_rawDescGZIP(), []int{0, 0}
}

// Indicates priority of delivery to prioritize critical events (e.g., CALL_OFFER).
type EventBroadcast_Priority int32

const (
	EventBroadcast_NORMAL EventBroadcast_Priority = 0
	EventBroadcast_HIGH   EventBroadcast_Priority = 1
)

// Enum value maps for EventBroadcast_Priority.
var (
	EventBroadcast_Priority_name = map[int32]string{
		0: "NORMAL",
		1: "HIGH",
	}
	EventBroadcast_Priority_value = map[string]int32{
		"NORMAL": 0,
		"HIGH":   1,
	}
)

func (x EventBroadcast_Priority) Enum() *EventBroadcast_Priority {
	p := new(EventBroadcast_Priority)
	*p = x
	return p
}

func (x EventBroadcast_Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventBroadcast_Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_event_payloads_v1_proto_enumTypes[1].Descriptor()
}

func (EventBroadcast_Priority) Type() protoreflect.EnumType {
	return &file_event_payloads_v1_proto_enumTypes[1]
}

func (x EventBroadcast_Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventBroadcast_Priority.Descriptor instead.
func (EventBroadcast_Priority) EnumDescriptor() ([]byte, []int) {
	return file_event_payloads_v1_proto_rawDescGZIP(), []int{2, 0}
}

// EventLink represents an event in the chat system, the core unit of data flowing
// through the system in real-time to end-user devices.
type EventLink struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the event, constrained for quick parsing and validation.
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Identifies the chat room or context, ensuring data is routed to the correct group.
	RoomId string `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	// Identifies the originator of the event, crucial for attribution and security.
	// Marked optional as it may not be required for system messages.
	SenderId *string `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3,oneof" json:"sender_id,omitempty"`
	// Unique identifier for a parent event related to this event, constrained for quick parsing and validation.
	ParentId string `protobuf:"bytes,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	// Categorizes the event (e.g., TEXT, ATTACHMENT) for efficient handling.
	EventType EventLink_EventType `protobuf:"varint,7,opt,name=event_type,json=eventType,proto3,enum=events.v1.EventLink_EventType" json:"event_type,omitempty"`
	// Timestamp for event creation, aiding in ordering and latency debugging.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventLink) Reset() {
	*x = EventLink{}
	mi := &file_event_payloads_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventLink) ProtoMessage() {}

func (x *EventLink) ProtoReflect() protoreflect.Message {
	mi := &file_event_payloads_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventLink.ProtoReflect.Descriptor instead.
func (*EventLink) Descriptor() ([]byte, []int) {
	return file_event_payloads_v1_proto_rawDescGZIP(), []int{0}
}

func (x *EventLink) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventLink) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *EventLink) GetSenderId() string {
	if x != nil && x.SenderId != nil {
		return *x.SenderId
	}
	return ""
}

func (x *EventLink) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *EventLink) GetEventType() EventLink_EventType {
	if x != nil {
		return x.EventType
	}
	return EventLink_SYSTEM
}

func (x *EventLink) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// EventReceipt represents an entry for delivery to a specific recipient,
// facilitating the distribution phase of data flow.
type EventReceipt struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifies the target user or device for precise routing.
	RecepientId string `protobuf:"bytes,1,opt,name=recepient_id,json=recepientId,proto3" json:"recepient_id,omitempty"`
	// Unique identifier for tracking delivery status and retries in real-time.
	TargetId      string `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventReceipt) Reset() {
	*x = EventReceipt{}
	mi := &file_event_payloads_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventReceipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventReceipt) ProtoMessage() {}

func (x *EventReceipt) ProtoReflect() protoreflect.Message {
	mi := &file_event_payloads_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventReceipt.ProtoReflect.Descriptor instead.
func (*EventReceipt) Descriptor() ([]byte, []int) {
	return file_event_payloads_v1_proto_rawDescGZIP(), []int{1}
}

func (x *EventReceipt) GetRecepientId() string {
	if x != nil {
		return x.RecepientId
	}
	return ""
}

func (x *EventReceipt) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

// EventBroadcast encapsulates an event and its delivery targets for bulk distribution
// to multiple recipients, optimizing the initial broadcast phase.
type EventBroadcast struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The event to be distributed.
	Event *EventLink `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	// List of delivery targets specifying recipients for batch processing efficiency.
	Targets       []*EventReceipt         `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
	Priority      EventBroadcast_Priority `protobuf:"varint,3,opt,name=priority,proto3,enum=events.v1.EventBroadcast_Priority" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventBroadcast) Reset() {
	*x = EventBroadcast{}
	mi := &file_event_payloads_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBroadcast) ProtoMessage() {}

func (x *EventBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_event_payloads_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBroadcast.ProtoReflect.Descriptor instead.
func (*EventBroadcast) Descriptor() ([]byte, []int) {
	return file_event_payloads_v1_proto_rawDescGZIP(), []int{2}
}

func (x *EventBroadcast) GetEvent() *EventLink {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *EventBroadcast) GetTargets() []*EventReceipt {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *EventBroadcast) GetPriority() EventBroadcast_Priority {
	if x != nil {
		return x.Priority
	}
	return EventBroadcast_NORMAL
}

// EventDelivery represents the final payload delivered to an end-user device,
// containing the event, specific delivery target, and detailed data.
type EventDelivery struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The event data being delivered.
	Event *EventLink `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	// Specific delivery target for this delivery, aiding in tracking.
	Target *EventReceipt `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// Flexible struct for detailed event data (e.g., message text, media metadata).
	Payload *structpb.Struct `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Indicates if payload data is compressed to save bandwidth for large messages.
	IsCompressed bool `protobuf:"varint,4,opt,name=is_compressed,json=isCompressed,proto3" json:"is_compressed,omitempty"`
	// Metadata for retry logic to ensure robust delivery to end-user devices.
	RetryCount    int32 `protobuf:"varint,5,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventDelivery) Reset() {
	*x = EventDelivery{}
	mi := &file_event_payloads_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventDelivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventDelivery) ProtoMessage() {}

func (x *EventDelivery) ProtoReflect() protoreflect.Message {
	mi := &file_event_payloads_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventDelivery.ProtoReflect.Descriptor instead.
func (*EventDelivery) Descriptor() ([]byte, []int) {
	return file_event_payloads_v1_proto_rawDescGZIP(), []int{3}
}

func (x *EventDelivery) GetEvent() *EventLink {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *EventDelivery) GetTarget() *EventReceipt {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *EventDelivery) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EventDelivery) GetIsCompressed() bool {
	if x != nil {
		return x.IsCompressed
	}
	return false
}

func (x *EventDelivery) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

var File_event_payloads_v1_proto protoreflect.FileDescriptor

const file_event_payloads_v1_proto_rawDesc = "" +
	"\n" +
	"\x17event_payloads_v1.proto\x12\tevents.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf1\x04\n" +
	"\tEventLink\x126\n" +
	"\bevent_id\x18\x01 \x01(\tB\x1b\xbaH\x18r\x16\x10\x03\x18(2\x10[0-9a-z_-]{3,20}R\aeventId\x124\n" +
	"\aroom_id\x18\x02 \x01(\tB\x1b\xbaH\x18r\x16\x10\x03\x18(2\x10[0-9a-z_-]{3,20}R\x06roomId\x12=\n" +
	"\tsender_id\x18\x03 \x01(\tB\x1b\xbaH\x18r\x16\x10\x03\x18(2\x10[0-9a-z_-]{3,20}H\x00R\bsenderId\x88\x01\x01\x128\n" +
	"\tparent_id\x18\x05 \x01(\tB\x1b\xbaH\x18r\x16\x10\x03\x18(2\x10[0-9a-z_-]{3,20}R\bparentId\x12=\n" +
	"\n" +
	"event_type\x18\a \x01(\x0e2\x1e.events.v1.EventLink.EventTypeR\teventType\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xf4\x01\n" +
	"\tEventType\x12\n" +
	"\n" +
	"\x06SYSTEM\x10\x00\x12\t\n" +
	"\x05EVENT\x10\x01\x12\b\n" +
	"\x04TEXT\x10\x02\x12\x0e\n" +
	"\n" +
	"ATTACHMENT\x10\x03\x12\f\n" +
	"\bREACTION\x10\a\x12\r\n" +
	"\tENCRYPTED\x10\x06\x12\b\n" +
	"\x04EDIT\x10\b\x12\r\n" +
	"\tREDACTION\x10\t\x12\x13\n" +
	"\x0fSTATE_DELIVERED\x10\n" +
	"\x12\x0e\n" +
	"\n" +
	"STATE_READ\x10\v\x12\x10\n" +
	"\fSTATE_TYPING\x10\f\x12\f\n" +
	"\bPRESENCE\x10\x11\x12\x0e\n" +
	"\n" +
	"CALL_OFFER\x10\x15\x12\x0f\n" +
	"\vCALL_ANSWER\x10\x16\x12\f\n" +
	"\bCALL_ICE\x10\x17\x12\f\n" +
	"\bCALL_END\x10\x18B\f\n" +
	"\n" +
	"_sender_id\"\x88\x01\n" +
	"\fEventReceipt\x12>\n" +
	"\frecepient_id\x18\x01 \x01(\tB\x1b\xbaH\x18r\x16\x10\x03\x18(2\x10[0-9a-z_-]{3,20}R\vrecepientId\x128\n" +
	"\ttarget_id\x18\x02 \x01(\tB\x1b\xbaH\x18r\x16\x10\x03\x18(2\x10[0-9a-z_-]{3,20}R\btargetId\"\xd1\x01\n" +
	"\x0eEventBroadcast\x12*\n" +
	"\x05event\x18\x01 \x01(\v2\x14.events.v1.EventLinkR\x05event\x121\n" +
	"\atargets\x18\x02 \x03(\v2\x17.events.v1.EventReceiptR\atargets\x12>\n" +
	"\bpriority\x18\x03 \x01(\x0e2\".events.v1.EventBroadcast.PriorityR\bpriority\" \n" +
	"\bPriority\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x00\x12\b\n" +
	"\x04HIGH\x10\x01\"\xe5\x01\n" +
	"\rEventDelivery\x12*\n" +
	"\x05event\x18\x01 \x01(\v2\x14.events.v1.EventLinkR\x05event\x12/\n" +
	"\x06target\x18\x02 \x01(\v2\x17.events.v1.EventReceiptR\x06target\x121\n" +
	"\apayload\x18\x03 \x01(\v2\x17.google.protobuf.StructR\apayload\x12#\n" +
	"\ris_compressed\x18\x04 \x01(\bR\fisCompressed\x12\x1f\n" +
	"\vretry_count\x18\x05 \x01(\x05R\n" +
	"retryCountB\x98\x01\n" +
	"\rcom.events.v1B\x14EventPayloadsV1ProtoP\x01Z,github.com/antinvestor/service-chat;eventsv1\xa2\x02\x03EXX\xaa\x02\tEvents.V1\xca\x02\tEvents\\V1\xe2\x02\x15Events\\V1\\GPBMetadata\xea\x02\n" +
	"Events::V1b\x06proto3"

var (
	file_event_payloads_v1_proto_rawDescOnce sync.Once
	file_event_payloads_v1_proto_rawDescData []byte
)

func file_event_payloads_v1_proto_rawDescGZIP() []byte {
	file_event_payloads_v1_proto_rawDescOnce.Do(func() {
		file_event_payloads_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_payloads_v1_proto_rawDesc), len(file_event_payloads_v1_proto_rawDesc)))
	})
	return file_event_payloads_v1_proto_rawDescData
}

var file_event_payloads_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_event_payloads_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_event_payloads_v1_proto_goTypes = []any{
	(EventLink_EventType)(0),      // 0: events.v1.EventLink.EventType
	(EventBroadcast_Priority)(0),  // 1: events.v1.EventBroadcast.Priority
	(*EventLink)(nil),             // 2: events.v1.EventLink
	(*EventReceipt)(nil),          // 3: events.v1.EventReceipt
	(*EventBroadcast)(nil),        // 4: events.v1.EventBroadcast
	(*EventDelivery)(nil),         // 5: events.v1.EventDelivery
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 7: google.protobuf.Struct
}
var file_event_payloads_v1_proto_depIdxs = []int32{
	0, // 0: events.v1.EventLink.event_type:type_name -> events.v1.EventLink.EventType
	6, // 1: events.v1.EventLink.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: events.v1.EventBroadcast.event:type_name -> events.v1.EventLink
	3, // 3: events.v1.EventBroadcast.targets:type_name -> events.v1.EventReceipt
	1, // 4: events.v1.EventBroadcast.priority:type_name -> events.v1.EventBroadcast.Priority
	2, // 5: events.v1.EventDelivery.event:type_name -> events.v1.EventLink
	3, // 6: events.v1.EventDelivery.target:type_name -> events.v1.EventReceipt
	7, // 7: events.v1.EventDelivery.payload:type_name -> google.protobuf.Struct
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_event_payloads_v1_proto_init() }
func file_event_payloads_v1_proto_init() {
	if File_event_payloads_v1_proto != nil {
		return
	}
	file_event_payloads_v1_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_payloads_v1_proto_rawDesc), len(file_event_payloads_v1_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_payloads_v1_proto_goTypes,
		DependencyIndexes: file_event_payloads_v1_proto_depIdxs,
		EnumInfos:         file_event_payloads_v1_proto_enumTypes,
		MessageInfos:      file_event_payloads_v1_proto_msgTypes,
	}.Build()
	File_event_payloads_v1_proto = out.File
	file_event_payloads_v1_proto_goTypes = nil
	file_event_payloads_v1_proto_depIdxs = nil
}
