name: Push proto to BSR
on:
  push:
    tags: ["v*"]
    paths: ["proto/**"]
jobs:
  buf-push:
    uses: antinvestor/common/.github/workflows/buf-push.yaml@main
    secrets:
      buf_token: ${{ secrets.BUF_TOKEN }}
