name: Changelog
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  changelog:
    permissions:
      contents: read
      pull-requests: write
    uses: antinvestor/common/.github/workflows/changelog.yml@main
