name: Draft Release
on:
  push:
    branches: [main]
jobs:
  draft:
    permissions:
      contents: write
      pull-requests: write
    uses: antinvestor/common/.github/workflows/draft-release.yml@main
