name: Release
on:
  push:
    tags: ["v*.*.*"]
jobs:
  docker:
    uses: antinvestor/common/.github/workflows/docker-release.yml@main
  buf-push:
    uses: antinvestor/common/.github/workflows/buf-push.yaml@main
    secrets:
      buf_token: ${{ secrets.BUF_TOKEN }}
  dart-publish:
    uses: antinvestor/common/.github/workflows/dart-publish.yml@main
    secrets:
      pub_credentials: ${{ secrets.PUB_DEV_CREDENTIALS }}
  opl-push:
    uses: antinvestor/common/.github/workflows/opl-push.yml@main
    secrets:
      deploy_token: ${{ secrets.DEPLOY_REPO_TOKEN }}
