name: Verify secrets
on: workflow_dispatch
jobs:
  hash:
    runs-on: ubuntu-latest
    steps:
      - name: Hash secrets
        run: |
          val="${ANDROID_SIGNING_KEY}"
          hash=$(printf "%s" "$val" | sha256sum | cut -d" " -f1)
          echo "ANDROID_SIGNING_KEY=$hash"
        env:
          ANDROID_SIGNING_KEY: ${{ secrets.ANDROID_SIGNING_KEY }}