name: Verify secrets
on: workflow_dispatch
jobs:
  hash:
    runs-on: ubuntu-latest
    steps:
      - name: Hash secrets
        run: |
          for name in ANDROID_KEYSTORE_PASSWORD ANDROID_SIGNING_KEY ANDROID_SIGNING_KEY_PASSWORD CLOUDFLARE_ACCOUNT_ID CLOUDFLARE_API_TOKEN FIREBASE_APP_ID_ANDROID FIREBASE_SERVICE_ACCOUNT GOOGLE_PLAY_SERVICE_ACCOUNT GOOGLE_SERVICES_JSON; do
            val="${!name}"
            hash=$(echo -n "$val" | sha256sum | cut -d" " -f1)
            echo "$name=$hash"
          done
        env:
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_SIGNING_KEY: ${{ secrets.ANDROID_SIGNING_KEY }}
          ANDROID_SIGNING_KEY_PASSWORD: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          FIREBASE_APP_ID_ANDROID: ${{ secrets.FIREBASE_APP_ID_ANDROID }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          GOOGLE_PLAY_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}