name: antinvestor_api_chat
description: Dart client library for Ant Investor Chat Service
version: 1.54.0
repository: https://github.com/antinvestor/service-chat
homepage: https://github.com/antinvestor/service-chat
issue_tracker: https://github.com/antinvestor/service-chat/issues

environment:
  sdk: ^3.3.0

dependencies:
  protobuf: ^4.2.0
  connectrpc: ^1.0.0
  fixnum: ^1.1.0
  antinvestor_api_common: ^1.52.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0

topics:
  - grpc
  - protobuf
  - api-client
  - chat
